# Generated by Django 4.2.1 on 2023-06-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_clientgroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientgroup',
            name='group_name',
            field=models.CharField(max_length=100, verbose_name='ClientGroup'),
        ),
    ]
